repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v3.15.0
  hooks:
    - id: pyupgrade
      args: [ --py310-plus ]

- repo: https://github.com/myint/autoflake
  rev: v2.2.1
  hooks:
      - id: autoflake
        args: [ '--in-place', '--remove-all-unused-imports', '--remove-unused-variable','--exclude=__init__.py' ]

- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
    - id: isort
      args: ["--profile", "black", "--filter-files"]

- repo: https://github.com/psf/black
  rev: 23.12.1
  hooks:
  - id: black
    language_version: python3.10

- repo: https://github.com/pycqa/flake8
  rev: 7.0.0
  hooks:
  - id: flake8

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.8.0
  hooks:
    - id: mypy
      args: ["--explicit-package-bases"]
      additional_dependencies:
        - pydantic
        - types-redis
        - types-requests