[mypy]
mypy_path = $MYPY_CONFIG_FILE_DIR/src
ignore_missing_imports = True
disallow_untyped_defs = True
disallow_any_generics = True
disallow_untyped_calls = True
disallow_incomplete_defs = True
check_untyped_defs = True

no_implicit_optional = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_return_any = True
implicit_reexport = False
strict_equality = True

# install packages to the pre-commit the re-enable this
# https://github.com/pre-commit/pre-commit/issues/1445

disallow_untyped_decorators = False
disallow_subclassing_any = False


[mypy-tests.*]
ignore_errors = True


[mypy-db.*]
ignore_errors = True